### ISSUE TITLE
Unable to sort on other fields than Id with connection (applied to mongoose plugin)

### ISSUE THREAD

**Issue by ziedHamdi** [graphql-compose/graphql-compose-connection#33]
Hi,

I have a weired issue: my entity is described as follows in mongoose:

**db/entity.js**
```
import mongoose from 'mongoose';
const EntitySchema = new mongoose.Schema({
	kind:{type:String, enum:["AS", "SERVICE", "PRODUCT"], required: true},
	name: {type: String, required: true, index: true},
	entityGroupId: {type: String, required: true},
	//TODO delete city
	city: String,
	img:String,
	barCode: String,

	fb: String,
	web: String,

	createdAt: {type:Date, index: true},
	updatedAt: {type:Date, index: true},

}, {timestamps : {}})


export default mongoose.model('Entity', EntitySchema)

```

its compose connection is as follows:
**graphql/entity.js**
```
import {composeWithMongoose} from 'graphql-compose-mongoose';
import {schemaComposer} from 'graphql-compose';

import {Entity, EntityGroup} from '../db'
import composeWithConnection from "graphql-compose-connection";

const customizationOptions = {}; // left it empty for simplicity, described below
const EntityTC = composeWithMongoose(Entity, customizationOptions)

const connectionResolver = composeWithConnection(EntityTC, {
	findResolverName: 'findMany',
	countResolverName: 'count',
	sort: {
		_ID_ASC: {
			value: {_id: 1},
			cursorFields: ['_id'],
			beforeCursorQuery: (rawQuery, cursorData, resolveParams) => {
				if (!rawQuery._id) rawQuery._id = {};
				rawQuery._id.$lt = cursorData._id;
			},
			afterCursorQuery: (rawQuery, cursorData, resolveParams) => {
				if (!rawQuery._id) rawQuery._id = {};
				rawQuery._id.$gt = cursorData._id;
			},
		},

		CREATEDAT_DESC: {
			value: {createdAt: -1},
			cursorFields: ['createdAt'],
			beforeCursorQuery: (rawQuery, cursorData, resolveParams) => {
				if (!rawQuery.createdAt) rawQuery.createdAt = null;
				rawQuery.createdAt.$lt = cursorData.createdAt;
			},
			afterCursorQuery: (rawQuery, cursorData, resolveParams) => {
				if (!rawQuery.createdAt) rawQuery.createdAt = null;
				rawQuery.createdAt.$gt = cursorData.createdAt;
			},
		},

		_ID_DESC: {
			value: {_id: -1},
			cursorFields: ['_id'],
			beforeCursorQuery: (rawQuery, cursorData, resolveParams) => {
				if (!rawQuery._id) rawQuery._id = {};
				rawQuery._id.$gt = cursorData._id;
			},
			afterCursorQuery: (rawQuery, cursorData, resolveParams) => {
				if (!rawQuery._id) rawQuery._id = {};
				rawQuery._id.$lt = cursorData._id;
			},
		}
	}
})

const addEntityNameRegexpSearch = function (resolverName) {
	const extendedResolver = EntityTC.getResolver(resolverName).addFilterArg({
		name: 'nameRegexp',
		type: 'String',
		description: 'Search by name in regExp',
		query: (query, value, resolveParams) => {
			query.name = new RegExp(value, 'i');
		},
	});
	extendedResolver.name = resolverName;
	EntityTC.addResolver(extendedResolver);
}

addEntityNameRegexpSearch('connection')
addEntityNameRegexpSearch('findMany')


schemaComposer.rootQuery().addFields({
	entityById: EntityTC.getResolver('findById'),
	entityByIds: EntityTC.getResolver('findByIds'),
	entityOne: EntityTC.getResolver('findOne'),
	entityMany: EntityTC.getResolver('findMany'),
	entityCount: EntityTC.getResolver('count'),
	entityConnection: EntityTC.getResolver('connection'),
});

schemaComposer.rootMutation().addFields({
	entityCreate: EntityTC.getResolver('createOne'),
	entityUpdateById: EntityTC.getResolver('updateById'),
	entityUpdateOne: EntityTC.getResolver('updateOne'),
	entityUpdateMany: EntityTC.getResolver('updateMany'),
	entityRemoveById: EntityTC.getResolver('removeById'),
	entityRemoveOne: EntityTC.getResolver('removeOne'),
	entityRemoveMany: EntityTC.getResolver('removeMany'),
});


export default schemaComposer;
```

**Now if I query the entity through its entityMany query sorting the result by the createdAt field, i get a result as exepcted:**
```
{
  entityMany(filter:{nameRegexp:"^a"}, sort:CREATEDAT_DESC) {
        _id,
        name,
        fb, 
        web,
				createdAt,
				updatedAt
      }
    }
```

**but if I attempt to do the query through the connection plugin, it fails with the message:**

```
{
  "errors": [
    {
      "message": "Expected type SortConnectionEntityEnum, found CREATEDAT_DESC.",
      "locations": [
        {
          "line": 2,
          "column": 60
        }
      ],
      "stack": [
        "Expected type SortConnectionEntityEnum, found CREATEDAT_DESC.",
        "",
        "GraphQL request (2:60)",
        "1: {",
        "2:   entityConnection(first:5, filter:{nameRegexp:\"^a\"}, sort:CREATEDAT_DESC) {",
        "                                                              ^",
        "3: \t\tcount",
        "",
        "    at Object.EnumValue (C:\\server\\node_modules\\graphql\\validation\\rules\\ValuesOfCorrectType.js:112:29)",...
      ],
      "zied": "oui"
    }
  ]
}
```
the query is the following, please notice that it accepts the two other sorting params : **_ID_ASC** and **_ID_DESC**, is there a place where i forgot to add **CREATEDAT_DESC** so I can query against it?
```
{
  entityConnection(first:5, filter:{nameRegexp:"^a"}, sort:CREATEDAT_DESC) {
		count
    pageInfo {
      startCursor,
      endCursor,
      hasNextPage,
      hasPreviousPage
    },
    edges {
      cursor,
      node {
        _id,
        name,
        fb, 
        web,
				createdAt,
				updatedAt
      }
    }
  }
}
```

**Comment by ziedHamdi** [comment]
the indexes are present in the db, i checked that first, but this is obvious since the entityMany query sorts correctly against the createdAt index:

> db.entities.getIndexes()
[
        {
                "v" : 2,
                "key" : {
                        "_id" : 1
                },
                "name" : "_id_",
                "ns" : "local.entities"
        },
        {
                "v" : 2,
                "key" : {
                        "createdAt" : 1
                },
                "name" : "createdAt_1",
                "ns" : "local.entities",
                "background" : true
        },
        {
                "v" : 2,
                "key" : {
                        "createdAt" : -1
                },
                "name" : "createdAt_-1",
                "ns" : "local.entities",
                "background" : true
        },
        {
                "v" : 2,
                "key" : {
                        "name" : 1
                },
                "name" : "name_1",
                "ns" : "local.entities",
                "background" : true
        },
        {
                "v" : 2,
                "key" : {
                        "updatedAt" : 1
                },
                "name" : "updatedAt_1",
                "ns" : "local.entities",
                "background" : true
        }
]
>

**Comment by ziedHamdi** [comment]
it doesn't work neither with a regular field  (not autogenerated by mongoose), **name** in this case:
```
		CREATEDAT_DESC: {
			value: {name: -1},
			cursorFields: ['name'],
			beforeCursorQuery: (rawQuery, cursorData, resolveParams) => {
				if (!rawQuery.createdAt) rawQuery.createdAt = null;
				rawQuery.createdAt.$lt = cursorData.createdAt;
			},
			afterCursorQuery: (rawQuery, cursorData, resolveParams) => {
				if (!rawQuery.createdAt) rawQuery.createdAt = null;
				rawQuery.createdAt.$gt = cursorData.createdAt;
			},
		},

```

**Comment by ziedHamdi** [comment]
Also I think there could be a utility function in the lib that accepts one parameter eg:

generateSortParam( {name:1, age:-1} ), that function can generate all necessary boilerplate code for the connection:

```
NAME_ASC_AGE_DESC : {
  value: {name: 1, age:-1},
			cursorFields: ['name', 'age'],
			beforeCursorQuery: (rawQuery, cursorData, resolveParams) => {
				if (!rawQuery.name) rawQuery.name = {];
				rawQuery.name.$gt = cursorData.name;
//etc...
			},
			afterCursorQuery: (rawQuery, cursorData, resolveParams) => {
//etc...
			},
		},
```

I think there's no need for a manual configuration in most cases

**Comment by nodkz** [comment]
Sorry for late response.

Take a look at how connection resolver initialized in mongoose https://github.com/graphql-compose/graphql-compose-mongoose/blob/master/src/resolvers/connection.js

There is one crucial thing - USED ONLY UNIQUE INDEXES
https://github.com/graphql-compose/graphql-compose-mongoose/blob/master/src/resolvers/connection.js#L37
It's required cause connection cursors should have uniq values among all records otherwise, the connection will work incorrectly. It may miss some records for the next portions of data.

**So if you add unique mongodb indexes to your model all will work out of the box. 😉**
**Connection does not work with non-unique indexes**

`generateSortParam` is a good suggestion, but it will work only for MongoDB. `graphql-compose-connection` implemented not only for MongoDB. So your suggested method should be in some other place or package. In `graphql-compose-mongoose` no need in such method, because should be used unique indexes.

PS. If you see some holes in docs or readme's, please open PR with unique index requirements. Thanks.

**Comment by ziedHamdi** [comment]
Thanks Pablo,

The issue was due to the fact that the field was not unique, but that's weired as a bahavior, since a sort should and had never been only on unique value fields...

**Comment by nodkz** [comment]
It's `cursor` requirement. Every cursor should be unique. And every cursor contains base64 data for fields that are used as SORT fields. Eg you are sorting by `createdAt` and `_id` so data from both fields passed to base64 cursor. When you try to request the next portion of data from DB, data from cursor will be used for `where` condition `{ createdAt: { $gt: value_from_cursor_for_createdAt }, _id: { $gt: value_from_cursor_for_id } }`.

So if cursor data will be non-unique then cursor-pagination may skip or return the same records.

**Comment by ziedHamdi** [comment]
Hi Pavel,

Thanks I understood the reason why the cursor is required to be unique, I persist though to think that the treatment of a sort field that is not unique should be handled differently by the library:
 - either by throwing an error to reject the field declaration saying that it has to be unique
 - or by accepting and generating a sort option with that field, writing a warning in the logs to say that side effects can be seen, since the sort field in not unique. (which is the option that I prefer)

I think the fact of silently ignoring the sort option is user unfriendly since we don't know what is the cause of it (unless we remember that unicity requirement)

Best regards,
Zied

**Comment by nodkz** [comment]
This package doesn't know which DB used under the hood. And cannot check indexes. So these checks cannot be applied here.

If you use this package with graphql-compose-mongoose then check must be done somewhere in  https://github.com/graphql-compose/graphql-compose-mongoose/blob/master/src/resolvers/connection.js#L37 Otherwise, it should be done in your code.

**Comment by ziedHamdi** [comment]
Yes I'm using graphql-compose-mongoose and that's where my sort option wasn't added to graphql until I added unique:true on it.

In my opinion, the loop should be sortConfigs.forEach instead of uniqueIndexes.forEach (https://github.com/graphql-compose/graphql-compose-mongoose/blob/master/src/resolvers/connection.js#L37) 
This way, sort options that don't meet prerequisits can raise warnings or errors

**Comment by ahelord** [comment]
how to sort by two indexes with grapqhl compose mongoose? for example
`{"sort":["_ID_ASC","LABEL_ASC"]}`

**Comment by nodkz** [comment]
@ahelord for now `graphql-compose-mongoose` supports sorting by indexed fields. And creates proper ENUM values according compound indexes for example `_ID_LABEL_ASC, _ID_LABEL_DESC`. It was done by performance reasons. But now i'm thinking to change this behavior in future versions of graphql-compose-mongoose to allow provide array of values for sorting.

Please re-open the issue in `graphql-compose-mongoose` for getting a notification when it will be done.

**Comment by ahelord** [comment]
Thanks @nodkz , you are a crack.

**Comment by Meandmybadself** [comment]
I believe that MongoDB IDs are created using the time of creation.
Sorting by a document's ID should provide the same sorting results as date of creation.
You can even get the item's timestamp from the ID: https://docs.mongodb.com/manual/reference/method/ObjectId.getTimestamp/
