### ISSUE TITLE
Is it possible to filter out edges after resolve?

### ISSUE THREAD

**Issue by toverux** [graphql-compose/graphql-compose-connection#39]
I'll explain myself better: I want to filter results server-side before they are returned to the client, but not by patching the Mongoose query, in my use case that's not an option although I known this would be more efficient.

Therefore, I want to remove some edges from the result once the final value is produced by the connection resolver, by wrapping the resolver and patching its return.

I know how to do that, but my question is about wether this could completely break how connections work or if this has no other impact than returning an unpredictable number of edges regardless the value of `limit`.
Watching the (quite complex) code of the resolver, I don't think this would break anything, but I'd be happy to have your insight.

Just filtering out the edges should be enough, but to do that properly, I think I'll also update `startCursor` to match the potentially new `edges[0].cursor` and `endCursor` to match `edges[edges.length - 1].cursor`.
Would that work intentionally? The only downsides that I see is that the number of results could vary unpredictably and that edges[] could even be empty if all documents in a slice are skipped, but that should pose no problems.

**Comment by nodkz** [comment]
Who knows 🤗
Need to test client apps which consume such connections with undetermined length.
According to Relay Cursor Connections Specification, clients must follow to [PageInfo](https://facebook.github.io/relay/graphql/connections.htm#sec-undefined.PageInfo) information from the server. So for Relay is required to provide proper not only `startCursor` and `endCursor `, also required data is `hasNextPage` and `hasPreviousPages`.
