### ISSUE TITLE
Connection with edge data

### ISSUE THREAD

**Issue by michaelbeaumont** [graphql-compose/graphql-compose-connection#50]
We're trying to tweak `graphql-compose-connection` to [add data to the edges](https://www.apollographql.com/blog/explaining-graphql-connections-c48b7c3d6976#f17b).
Concretely, we have an m-to-n relationship in mongo linking to collections `X` and `Y` using a collection `XY` which has data itself:
```
XY = new mongoose.Schema({
  xId: ObjectId,
  yId: ObjectId,
  kind: String,
})
```

Ideally, I'd like to have the following schema:
```
xs {
  <x fields>
  ys {
    edges {
      kind  // <- comes from `XY`
      node {
        <y fields>
      }
    }
  }
}
```

How could `graphql-compose-connection` support this?

Some things aren't clear, like how to do filtering, how to deal with indexes.

Our current idea for filtering would allow for something like:
```
ys(filter: { node: {<y fields>}, edge: { kind: "kind1" } }) {
```

where I can do filtering both on the edge and the node.

What do you think? We have a [WIP](https://github.com/michaelbeaumont/graphql-compose-connection/commits/mb/expand_edge)

**Comment by nodkz** [comment]
For such complex case, I recommend you write field resolver from scratch. It will be faster and more configurable.

Also, you may try to use `addRelation` method:
- https://github.com/graphql-compose/graphql-compose/issues/94
- https://github.com/graphql-compose/graphql-compose/issues/43

But I found that `addRelations` complex in some situations and it's may lead to some complex debuggable situations.

So don't get in trap with code generation with such case. Just write such resolver manually and you save your time.

**Comment by nodkz** [comment]
For such complex case, I recommend you write field resolver from scratch. It will be faster and more configurable.

Also, you may try to use `addRelation` method:
- https://github.com/graphql-compose/graphql-compose/issues/94
- https://github.com/graphql-compose/graphql-compose/issues/43

But I found that `addRelations` complex in some situations and it's may lead to some complex debuggable situations.

So don't get in trap with code generation with such case. Just write such resolver manually and you save your time.

**Comment by michaelbeaumont** [comment]
The point of using connection would be to get all of the pagination, cursor etc "for free".
My plan at the moment is to write the resolver manually, but some tweaks to `connection` are needed, for creating the edge type and tweaking the output to match that type.

**Comment by nodkz** [comment]
Open PR and let discuss proposed changes.

PS. we should try to keep runtime changes as small as possible for this package. we should try to avoid performance degradation.

**Comment by PeteMac88** [comment]
> Open PR and let discuss proposed changes.
> 
> PS. we should try to keep runtime changes as small as possible for this package. we should try to avoid performance degradation.

Hey, any news when you will have a look at the proposed changes in the PR?

**Comment by nodkz** [comment]
@michaelbeaumont  sorry for the delay. I completely lose your PR. Sorry! 🙏
@PeteMac88 thanks for pinging me 👍
