### ISSUE TITLE
Option for defining name for edgeType

### ISSUE THREAD

**Issue by PeteMac88** [graphql-compose/graphql-compose-connection#52]
With the changes we made in https://github.com/graphql-compose/graphql-compose-connection/issues/50 the connection resolver becomes much more flexible. The problem i have now is that thetype name for the edge of the connection resolver is always dereived from the node type

https://github.com/graphql-compose/graphql-compose-connection/blob/d9df62600bd4de0028c7ff0b3e1d8e7cfd67af00/src/types/connectionType.js#L54

I would propose to extend the `ComposeWithConnectionOpts` with `edgeTypeName` as followed:

```
export type ComposeWithConnectionOpts<TContext> = {
  connectionResolverName?: string,
  findResolverName: string,
  countResolverName: string,
  sort: ConnectionSortMapOpts,
  defaultLimit?: ?number,
  edgeTypeName?: string,
  edgeFields?: ObjectTypeComposerFieldConfigMap<any, TContext>,
};
```

I would also do an additional change to [`graphql-compose-mongoose`](https://github.com/graphql-compose/graphql-compose-mongoose) to use this new option through the [`connection`](https://github.com/graphql-compose/graphql-compose-mongoose/blob/a880f3eaa9f33f337539d80879157e8b89e92864/src/resolvers/connection.js#L24)  function.

Short feedback would be appriciated. Thanks!

**Comment by nodkz** [comment]
Geat! Let's improve it.

**Comment by nodkz** [comment]
@PeteMac88 btw in [graphql-compose@7.15.0](https://github.com/graphql-compose/graphql-compose/releases/tag/v7.15.0) were added useful getters which help to write less code:

```diff
const UserTC = schemaComposer.createObjectTC(`type User { name: String }`);
schemaComposer.Query.addFields({
   // equivalent to SDL `users: [User!]`
-  users: { type: new ListComposer(new NonNullComposer(UserTC))}
-  users: { type: UserTC.getTypeNonNull().getTypePlural() }
+  users: { type: UserTC.NonNull.List }
});
```

**Comment by PeteMac88** [comment]
Hey can you release a new version?

**Comment by nodkz** [comment]
Sorry. I missed with correct name for commit message. 

Now added a new one with `feat:`. Semantic-release publishes new package automatically with `feat:`, `fix:` prefixes.
