### ISSUE TITLE
Wrong algorithm for pageInfo.hasPreviousPage and pageInfo.hasNextPage?

### ISSUE THREAD

**Issue by Hybrid-Force** [graphql-compose/graphql-compose-connection#54]
Thanks for the amazing library, first of all!

Please correct me if I am wrong, it seems that the algorithm for `pageInfo.hasPreviousPage` and `pageInfo.hasNextPage` fields are not following with the [cursor connections spec](https://relay.dev/graphql/connections.htm#HasPreviousPage()).
https://github.com/graphql-compose/graphql-compose-connection/blob/29269dde58c72333fb853c7037f2cdd58be489aa/src/connectionResolver.js#L338-L339

With current implementation, in forward pagination situation with `first/after`, `pageInfo.hasPreviousPage` is always set to `false`. And `pageInfo.hasNextPage` always `false` in backward pagination. In forward pagination, `pageInfo.hasNextPage` is only working with `first` and `last` both set, which is [discouraged](https://relay.dev/graphql/connections.htm#note-a97ec).

I am wondering if this deviation from the spec is intentional or is it a potential bug?

**Comment by nodkz** [comment]
It looks like a bug. Can you provide test case or send a pull request?

**Comment by Hybrid-Force** [comment]
> It looks like a bug. Can you provide test case or send a pull request?

Sure, I will try put together a pull request.
